version: "3.1"

services:
  rabbitmq:
    image: rabbitmq:management
    restart: no
    ports:
      - "5672:5672"
      - "15672:15672"
  database:
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password